/*
 * frank-msx — fMSX for RP2350
 *
 * Copyright (c) 2026 Mikhail Matveev <xtreme@rh1.tech>
 * https://github.com/rh1tech/frank-msx
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * msx_bios.c — built-in MSX1 BIOS pointer.
 *
 * fMSX's LoadROM("MSX.ROM", 0x8000, 0) is called from ResetMSX when the model
 * flips to MSX1. We don't redirect that path here; instead the Pico file-IO
 * layer (src/Pico/fileio.c) makes fopen("MSX.ROM","rb") resolve to the
 * FatFS SD card mount, so dropping MSX.ROM on the SD card is enough.
 *
 * If you prefer to link a BIOS blob into the firmware, drop a C BIOS array
 * into msx_bios_blob.h (generated by `xxd -i MSX.ROM > msx_bios_blob.h`),
 * set HAVE_EMBEDDED_MSX_BIOS, and the vfs shim will serve it from memory.
 *
 * Legal note: the MSX BIOS is copyright Microsoft/ASCII. Shipping it inside
 * firmware images requires a license, so the default build ships no BIOS.
 */
#include <stddef.h>
#include <stdint.h>

/* When HAVE_EMBEDDED_MSX_BIOS is defined, provide a linked-in blob. */
#ifdef HAVE_EMBEDDED_MSX_BIOS
#include "msx_bios_blob.h"   /* must define MSX_ROM[] + MSX_ROM_LEN */
#else
const unsigned char *MSX_ROM = NULL;
const unsigned int   MSX_ROM_LEN = 0;
#endif
